module.exports = {
  MONGODB_USER: process.env.MONGODB_USER,
  MONGODB_PASSWORD: process.env.MONGODB_PASSWORD,
  MONGODB_DATABASE: process.env.MONGODB_DATABASE,
  MONGODB_LOCAL_PORT:process.env.MONGODB_LOCAL_PORT,
  MONGODB_DOCKER_PORT: process.env.MONGODB_DOCKER_PORT,
  MONGODB_HOST: process.env.MONGODB_HOST,
};